language: go

matrix:
  include:
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env: GO111MODULE=on
    - go: "1.12.x"
      env: GO111MODULE=on
    - go: "tip"
      script:
        - go test -v --coverprofile=cover.out ./...
        - go get github.com/mattn/goveralls
        - goveralls --coverprofile=cover.out --service=travis-ci
