name: Test
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x
          - 1.18.x
          - 1.19.x
          - 1.20.x
          - 1.21.x
          - 1.22.x
          - 1.23.x
          - 1.24.x
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}
      - name: Download Go modules
        run: go mod download
      - name: Test Go code
        run: go test -v -race -covermode atomic -coverprofile coverage.out ./...
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          disable_search: true
          files: coverage.out
