name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.13.x"
          - "1.14.x"
          - "1.15.x"
          - "1.16.x"
          - "1.17.x"
          - "1.18.x"
          - "1.19.x"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}
      - name: Download Go modules
        run: go mod download
      - name: Run Go test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage profile
        uses: codecov/codecov-action@v3
        with:
          file: coverage.out
